In [35]:
import pandas as pd

In [47]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [73]:
# feature engineering
# apply() - this fxn will add the new coloumn in the existing data

df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%")
# here it added tax colm, the tax is calculatd by using income

# map() - this fxn helps to mapped the values 
# suppose we wanna convert the Male - M, Female - F, Unknown - U we will use map() fxn
gender_map = {"Male" : "M","Female": "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)


# assign() - this fxn assign a new coloumn and new vals to that colm
df2 = df2.assign(new_income = df2["income"] * 1.1) 


# replce() - change and replace the value
df2["country"] = df2["country"].replace("USA", "US")


# rename
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index={1:"First"})


# sorting values
df2 = df2.fillna(50)
df2.sort_values("Income") #ye ascendingorder me print hoga
df2.sort_values("Income", ascending=False) #if we want in descending order
sorted_df = df2.sort_values(["Income", "Age"]) #if income dono ka same hoga to age ke basis pe sorting hogi

# index sorting
sorted_df.sort_index()

# reset() - isme humara data as it is rahega aur sirf index sort hoga
sorted_df.reset_index()
sorted_df.reset_index(drop=True) #agar hum chahte hai ki hamari index preserve na ho aur vo reset ho jaye


# ranking- assign the rank from lowest to highest
sorted_df["Ranking"] = sorted_df["Income"].rank()
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False) #reverse in descending order highest to lowest
# it will assign the rank on the basis of the income

# sorted_df["Ranking"] = sorted_df["Income"].rank(method = "dense", method = "max" ) dense- if values are both same then assign only one, max- assign max value

sorted_df


# if we wanna switch the places of coloumns
sorted_df[["Id", "Name", "Age", "Country", "Gender", "Income", "New_Income", "Tax"]] 
# tax will get shifted to the last

    Id          Name   Age Country Gender   Income  New_Income  Tax
4    4  Maria Garcia  34.0   Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0     49500.0  10%
3    3          Alex  50.0      US      U  47000.0     51700.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  10%
0    1      John Doe  29.0      US      M  55000.0     60500.0  10%
1    1      John Doe  29.0      US      M  55000.0     60500.0  10%
10  10   Emily Davis  31.0      US     50  58000.0     63800.0  10%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0      50      M  68000.0     74800.0  20%
6    6            50  45.0   India      F  73000.0     80300.0  20%

In [63]:
df2

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0