In [2]:
#  access csv data
import pandas as pd

In [28]:
df = pd.read_csv("employee_data.csv")
print(df)
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [40]:
# methods
df.head() #print starting 5 rows 
# 5 rows yahape by default print ho rahi hai hum apane man se bhi print kar sakate hai
df.head(3)

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
2   2  Jane Smith   NaN  Canada  Female  62000.0

In [33]:
df.tail()

#prints last 5 rows # yaha by default 5 rows print ho rahi hai hum apane hisab se kitane bhi print kar sakate hai agar humane suppose 3 value pass ki to 3 rows print hoge

    id         name   age country  gender   income
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [34]:
df.sample()

#koi bhi random sample row print hogi

   id      name   age country gender   income
0   1  John Doe  29.0     USA   Male  55000.0

In [35]:
df.info()

#summary of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

In [36]:
df.shape 

#give tuples of data like (row*coloumn), yahape 10 rows hau & 5 columns

(11, 6)

In [37]:
df.describe() 

#gives numerical calculation

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [38]:
df.columns

#prints the columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [39]:
df.nunique()

#prints the unique values

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64