In [1]:
import pandas as pd

In [6]:
# DataFrames using the dictonary of list

info = {
    "Name" : ["Shrutika", "Devanshi", "Prachi", "Shravani"],
    "Age" : [23, 21, 24, 25],
    "CGPA" : [9.27, 8.73, 8.90, 9.07]
}

df = pd.DataFrame(info)

print(df, type(df))

print(df.index) # it shows row indices. RangeIndex(start=0, stop=4, step=1), it means index start from zero, stops means total 4 index and each are seperated using 1 step 
print(df.columns) #to access the column values

       Name  Age  CGPA
0  Shrutika   23  9.27
1  Devanshi   21  8.73
2    Prachi   24  8.90
3  Shravani   25  9.07 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [7]:
df

       Name  Age  CGPA
0  Shrutika   23  9.27
1  Devanshi   21  8.73
2    Prachi   24  8.90
3  Shravani   25  9.07

In [15]:
# DataFrames using the list of list
df = pd.DataFrame([["Shanku", 21], ["Kiki", 23], ["PG", 24], ["Suga", 26]], columns = ["Name", "Age"])
print(df)
df

     Name  Age
0  Shanku   21
1    Kiki   23
2      PG   24
3    Suga   26

     Name  Age
0  Shanku   21
1    Kiki   23
2      PG   24
3    Suga   26

In [17]:
# DataFrames using the numpy array
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd. DataFrame(np_arr, columns = ["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6